---
- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes and only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt: update_cache=yes upgrade=full force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
      
    - name: Ensure update-manager-core is installed.
      apt: name=update-manager-core state=present
     
    - name: Run do-release-upgrade non-interactively.
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      when: ansible_facts['distribution_major_version']=="18.04"
      
    - name: Remove useless ackages from the cache and remove dependencies that are no longer required
      apt:
        autoclean: yes
        autoremove: yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
 
 #   Use he reboot module for ansible 2.7+
 #   - name: Reboot the server
 #     command: reboot
 #     async: 0
 #     poll: 0
      
